language: elixir
elixir:
  - 1.4.5
  - 1.5.3
  - 1.6.4
otp_release:
  - 19.3
  - 20.3

before_script:
  - MIX_ENV=test mix compile --warnings-as-errors
  - travis_wait mix dialyzer --plt
script:
  - mix credo --strict
  - if [[ "$TRAVIS_ELIXIR_VERSION" == "1.6"* ]]; then mix format --check-formatted; fi
  - mix dialyzer --halt-exit-status
  - mix safe_coveralls.travis
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
sudo: required
dist: trusty
cache:
  directories:
    - _build
    - deps
